# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :year/:month/:title.html
relative_permalinks: true

# Setup
title:               明天蔚蓝
tagline:             '我想去看看这个世界'
description:         '随想，妄想，狂想，思想'
url:                 http://mwzhang.com
baseurl:             /cn
paginate:            5

# About/contact
author:
  name:              Mingwei Zhang
  url:               http://mwzhang.com
  email:             mingwei@mwzhang.com

# Custom vars
version:             1.0.0
